name: Docker Image CI MS Clientes

on:
  push:
    branches: [ MSClientes ]
  pull_request:
    branches: [ MSClientes ]

env:
  IMAGE_NAME: ms_clientes_uv
  VERSION: $(date +%s)
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $DOCKER_USER/$IMAGE_NAME

    - name: Log into registry
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Push image
      run: docker push $DOCKER_USER/$IMAGE_NAME
